###
GET http://localhost:8080/api/tutorials

###
GET http://localhost:8080/api/tutorials/1

###
GET http://localhost:8080/api/tutorials/published

###
GET http://localhost:8080/api/tutorials?title=Book

###
POST http://localhost:8080/api/tutorials
Content-Type: application/json

{
  "title": "First Book",
  "description": "First Book",
  "published": false
}

###
PUT http://localhost:8080/api/tutorials/1
Content-Type: application/json

{
  "title": "First Book",
  "description": "First Book",
  "published": true
}

###
DELETE http://localhost:8080/api/tutorials/1

###
DELETE http://localhost:8080/api/tutorials

